### ISSUE TITLE
is it possible  to have  svg map pan zoom?

### ISSUE THREAD

**Issue by yaman3bd** [VictorCazanave/vue-svg-map#26]
I'm using the map to display the users stats based on their country or region but there are some countries that are too small to be seen so is it possible to have  SVG map pan zoom like [the same zoom in this map demo](https://codepen.io/delarge/pen/rWBeBw)?
also, thanks for this amazing package saved me lots of time!

**Comment by yaman3bd** [comment]
Also is it possible to add the Continents as an individual map?
Like, in the same way, I get the USA map I can get Europe or Asia or The Arab world, etc
and if there is the possibility to make the maps searchable 
Like when I search for  a specific country in the search bar only the map that matched the search shows up
I wanted those features because most of the users in my project are placed in The Arab world and there are some countries that are too small! like Lebanon, Qatar, Bahrain they even can not be seen to hover the mouse over them!

**Comment by VictorCazanave** [comment]
> I'm using the map to display the users stats based on their country or region but there are some countries that are too small to be seen so is it possible to have SVG map pan zoom like the same zoom in this map demo?

Since this component generates an SVG, I think you can use a library like [panzoom](https://github.com/anvaka/panzoom) (or its vue version [vue-panzoom](https://github.com/thecodealer/vue-panzoom)) to handle it.
I've done a [quick test](https://codesandbox.io/s/vue-svg-map-pan-zoom-2lv09) which seems to work well.

> Also is it possible to add the Continents as an individual map?

You can create and import your own maps. Or you can open an issue in [@svg-maps project](https://github.com/VictorCazanave/svg-maps/issues), but I don't know when I have time to do it. So any contributions are welcome! 👼 

> and if there is the possibility to make the maps searchable

It's possible but you have to implement it by yourself. [Here](https://codesandbox.io/s/vue-svg-map-search-mpo9o) is a quick example that you can adjust to fit your needs.

> also, thanks for this amazing package saved me lots of time!

You're welcome! I'm glad this package is useful to some people 😀

**Comment by VictorCazanave** [comment]
@yaman3bd if your issue is not fixed, feel free to re-open it.

**Comment by gregpalaci** [comment]
This is a great demo, what I was looking for also... might be worth adding it as an example?

**Comment by gregpalaci** [comment]
darn the events seem to get swallowed by vue-pan-zoom and not fire on vue-svg-map, probably not an easy solution?

**Comment by VictorCazanave** [comment]
> This is a great demo, what I was looking for also... might be worth adding it as an example?

Yes, it's a good idea!

> darn the events seem to get swallowed by vue-pan-zoom and not fire on vue-svg-map, probably not an easy solution?

Do you mean that `vue-svg-map` doesn't emit events anymore? I've done a [quick test](https://codesandbox.io/s/vue-checkbox-svg-map-pan-zoom-mq45h) and it seems to work well.

**Comment by gregpalaci** [comment]
Weird for me none of the clicks were getting through,
Thanks for the quick test it's brilliant and I can work off that.
cheers
