### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by jonyedu** [VictorCazanave/vue-svg-map#55]
Hello,

In advance, thank you very much for the package, it is very easy to use and very good.

Will the zoom functionality ever arrive?

Excuse my writing, I'm not very good with English.

**Comment by VictorCazanave** [comment]
Hi,
I don't plan to implement a zoom functionnality, because I would like to keep these components as simple as possible and only generate SVG.
You can use another component, like [vue-panzoom](https://github.com/thecodealer/vue-panzoom), to wrap the map and add a zoom.
(Hope my reply is not too late 😅)

**Comment by VictorCazanave** [comment]
Actually, https://github.com/VictorCazanave/vue-svg-map/issues/26 is similar to your request and contains an example.
