### ISSUE TITLE
Add markers on map

### ISSUE THREAD

**Issue by valh1996** [VictorCazanave/vue-svg-map#8]
Hello,

Is it planned to have the possibility to add markers on the map please?

It would indeed seem very interesting to be able to add markers and to have a label by placing the mouse on it.

Thank you for your work!
Val'

**Comment by VictorCazanave** [comment]
Hi @valh1996 ,

I'm not familiar with markers but if I understand well, adding a slot after `<svg>` tag and handling the `marker-start` and `marker-end` attributes (or any custom attributes) should be enough.
Then the user can define the markers in the slot and [customize the map](https://github.com/VictorCazanave/vue-svg-map#modify-a-map) to add `<path>` attributes.
What do you think?

Could you show an example of markers on a map please? I'm curious to see how it can be used 😃

**Comment by valh1996** [comment]
Yes, your solution also seems interesting.

In fact, there is no notion of latitude/longitude, so I was thinking of adding a marker in the middle of the desired area.

For my example (based on [JsFiddle](https://jsfiddle.net/dYuAA/114/)), I used  _[document.createElementNS](https://developer.mozilla.org/fr/docs/Web/API/Document/createElementNS)_ to add a marker to the map. I think it's a reliable solution, what do you think? This would allow us to add different types of markers: text, shapes, images, etc.

_(In this example, I took a random icon from the internet)_
```js
function addMarker(location) {
  if (!location) return;

  let path = document.getElementById(location);
  if (path) {
    let iconMarker = document.createElementNS('http://www.w3.org/2000/svg','image');
    const box = path.getBBox();
    iconMarker.setAttributeNS(null, 'height', '30');
    iconMarker.setAttributeNS(null, 'width', '30');
    iconMarker.setAttributeNS('http://www.w3.org/1999/xlink','href', 'https://img.icons8.com/ios-glyphs/30/000000/marker-storm.png');
    iconMarker.setAttribute("transform", "translate(" + (box.x + box.width / 2) + " " + (box.y + box.height / 2) + ")");
    path.parentNode.insertBefore(iconMarker, path.nextSibling);
  }
}

addMarker('us')
```

However, this solution does not appear to be fully functional. I use the world map and for some countries the markers are not correctly placed or placed underneath (bad z-index). Maybe you have an idea how to place the marker always in the right zone ?

**Comment by VictorCazanave** [comment]
I tested your solution and I also think it's reliable 👍 

Replacing `path.parentNode.insertBefore(iconMarker, path.nextSibling)` by `path.parentNode.appendChild(iconMarker)` seems to fix the markers placed underneath.

To place the marker really in the middle of the location, the translation should be `(box.x + (box.width / 2) - 15) + " " + (box.y + (box.height / 2) - 15)` (`15` is half of the size of the icon). 
However some countries may need a specific position because they contain islands or separate parts:
* Australia with a small island at the bottom right corner: 
![image](https://user-images.githubusercontent.com/8233304/79411572-b6366080-7fd5-11ea-997c-2b0b9e51445a.png)
* USA with Alaska state:
![image](https://user-images.githubusercontent.com/8233304/79411529-a3239080-7fd5-11ea-999a-59e2b1d9b050.png)

If I have time this week, I will add slots in the components. Then we can take advantage of Vue and avoid to manipulate the DOM to add the markers.
Or if you know how to do it, feel free to open a pull request!

**Comment by valh1996** [comment]
Fine, I would have liked to contribute, but I've never done unit tests like this before.

I've tried to modify the package, but whatever I do, i get this error when running tests (with _"--updateSnapshot"_ param):
`[Warn view]: Error in v-on handler: "TypeError: location.focus is not a function"`

**Comment by VictorCazanave** [comment]
> Fine, I would have liked to contribute, but I've never done unit tests like this before.
I've tried to modify the package, but whatever I do, i get this error when running tests (with "--updateSnapshot" param):
[Warn view]: Error in v-on handler: "TypeError: location.focus is not a function"

No worries! It's not easy to fix the tests of someone else's component 😅 
This error was due to the slots because now the SVG may contain other elements than `<path>`. If you are interested, it has been fixed at [this line](https://github.com/VictorCazanave/vue-svg-map/pull/10/files#diff-1ee12503f1417b5c80d79366d24209d2R120).

> On the other hand, you were thinking of a totally free slot to put whatever we want inside? In this case the positioning would be based on which data?

I think a slot before and a slot after all the locations (`<path>`) are enough to customize the map.

> PS : It also seems that in small countries like Switzerland, you don't even see the country anymore.

Yes, if the marker is bigger than the location, it hides it. A solution may be to choose a smaller marker or to adjust its size according to the location's size.

**Comment by VictorCazanave** [comment]
@valh1996 a new version of the package has been published containing slots (https://github.com/VictorCazanave/vue-svg-map/pull/10) and custom attributes (https://github.com/VictorCazanave/vue-svg-map/pull/11). Feel free to reopen the issue if it doesn't help to handle markers.
